### ISSUE TITLE
Code is not orthogonal sometimes

### ISSUE THREAD

**Issue by danscu** [coen233s/OVSF_CDMA#2]
Reproduce:
  Modify Configuration.h: change TEST_CODE_RANGE to 1.
  Compile and run TestCdma 

Symptoms:
   Mobile #2 send handshake to BS successful
   Mobile #3 send handshake to BS but first byte 0xCC is received as 0x30. 

Analysis:
   This is due to collision with data in the data channel. Because different channels should not interference, the code is wrong.
   Control channel code [1, ... ,1] -- 16 ones
   Mobile 2: [1 1 1 1 1 1 -1 -1]
   Dot product: -4 (first 8 chips)

**Comment by coen233s** [comment]
The basestation #2 actual code is [ 1 1 -1 -1]. The reason TestCDMA printed out the code for Mobile #2 as [1 1 1 1 1 1 -1 -1] instead of the correct code because the control frame uses 8-bit data array to store walsh code.

The code [1 1 -1 -1] is represented as 4-bit chip code, 0xc - but MobileStation.cpp treats it as 0xfc, which is not correct. Therefore, it constructed a wrong code and therefore, code is not orthogonal with the control channel code.

I set the smallest code length to 8. This will fix this issue.
